version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grocery-qp  
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=grocery_password
      - DB_NAME=grocery_db
      - JWT_SECRET=secret_qp_key
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=grocery_password
      - MYSQL_DATABASE=grocery_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  mysql_data:
